### ISSUE TITLE
✨ [Feat] Assignment 2 (메모장 어플 만들기) 

### ISSUE THREAD

**Issue by wjdalswl** [wjdalswl/Yourssu-Incubating#5]
## 📝 개요
- 메모장 어플 만들기

## ⭐️ Pass 
- [x] UITableView를 올바르게 사용하였고 메모를 추가하면 화면이 자동으로 홈화면으로 돌아오는가?
- [x] 이 때 추가한 메모가 자동으로 리스트에 반영되는가?
- [x] 리스트 아이템을 터치하였을 때 상세 화면이 나오고 올바르게 데이터가 전달되는가?

## ✔️ To-do
- [x] MVVM + Coordinator 패턴
- [x] RxSwift(or Combine) 활용 => Combine활용
- [x] Clean Architecture
