### ISSUE TITLE
✨ [Feat] Assignment 3 (네트워크 연결 및 YDS 사용)

### ISSUE THREAD

**Issue by wjdalswl** [wjdalswl/Yourssu-Incubating#7]
## 📝 개요
- YDS(Yourssu Design System)을 이용하여 간단한 API 연결앱 만들기

## ⭐️ Pass 
- [x] 네트워크 통신이 잘 이루어졌는가?
- [x] YDS를 사용하여 UI를 올바르게 구현했는가?

## ✔️ To-do
- [x] MVVM + Coordinator 패턴
- [x] RxSwift(or Combine) 활용
- [x] Clean Architecture
